### ISSUE TITLE
Got the latest version related error when doing composer install

### ISSUE THREAD

**Issue by rama-tm** [dotmailer/dotmailer-magento2-extension-graph-ql#2]
I got the below error when I tried to do the **composer install**
![image](https://github.com/dotmailer/dotmailer-magento2-extension-graph-ql/assets/59078028/924059cf-e55f-4097-be03-7ff984514a46)

And I noticed this module was upgraded just 3 hours ago of doing this. Why is not updated in the private repo?

I got some fixes to resolve this.

Update the below code composer.json file.
1. magento/composer-dependency-version-audit-plugin -> false

2. "repositories": [
        {"type": "composer", "url": "https://repo.magento.com/", "canonical":  false},
]

Ref: https://www.rakeshjesadiya.com/composer-higher-matching-version-of-modules-was-found-in-public-repository-than-version-in-private-issue/

Is this the proper way to resolve this? and any other proper way to resolve this?

**Comment by sta1r** [comment]
@rama-tm Hi, sorry we've taken so long to respond. I think this happened because we tagged the code on Github (thus triggering an update to Packagist) before the package had completely published into repo.magento.com. 

You shouldn't have to set `"canonical": false` (we should be more careful) but yes that is one way to resolve it.
